/// Payload for an Info Card response (e.g. Venue, Location, Offer).
class CardPayload {
  final String title;
  final String description;
  final String? linkUrl;
  final String? ctaNote;
  final String? imageUrl;

  const CardPayload({
    required this.title,
    required this.description,
    this.linkUrl,
    this.ctaNote,
    this.imageUrl,
  });

  factory CardPayload.fromJson(Map<String, dynamic> json) {
    return CardPayload(
      title: json['title'] ?? json['cardTitle'] ?? '',
      description: json['description'] ?? json['desc'] ?? '',
      linkUrl: json['linkUrl'] ?? json['url'],
      ctaNote: json['ctaNote'] ?? json['cta'],
      imageUrl: json['imageUrl'] ?? json['image'],
    );
  }

  /// Parses Card HTML or fallback string generated by CRM Card Builder.
  /// Example: "<div class='card'><div class='card-title'>Axiata Tower</div><div class='small'>Private office...</div></div>"
  static CardPayload? parseFromHtmlOrText(String html) {
    if (!html.contains("class='card'") && !html.contains('class="card"')) {
      return null;
    }

    String title = '';
    String description = '';
    String? linkUrl;
    String? ctaNote;

    final titleMatch = RegExp(r"class=['\x22]card-title['\x22]>([^<]+)<").firstMatch(html);
    if (titleMatch != null) {
      title = titleMatch.group(1) ?? '';
    }

    final smallMatch = RegExp(r"class=['\x22]small['\x22]>([\s\S]*?)<\/div>").firstMatch(html);
    if (smallMatch != null) {
      String rawDesc = smallMatch.group(1) ?? '';
      // Extract link if present
      final urlMatch = RegExp(r'https?:\/\/[^\s<]+').firstMatch(rawDesc);
      if (urlMatch != null) {
        linkUrl = urlMatch.group(0);
        rawDesc = rawDesc.replaceAll(RegExp(r'Explore this space in detail here:\s*https?:\/\/[^\s<]+'), '');
      }
      description = rawDesc.replaceAll('<br/>', '\n').replaceAll('<br>', '\n').trim();
    }

    final ctaMatch = RegExp(r"class=['\x22]cta-note['\x22]>([^<]+)<").firstMatch(html);
    if (ctaMatch != null) {
      ctaNote = ctaMatch.group(1);
    }

    if (title.isEmpty && description.isEmpty) return null;

    return CardPayload(
      title: title.isEmpty ? 'CEO Suite Location' : title,
      description: description,
      linkUrl: linkUrl,
      ctaNote: ctaNote,
    );
  }

  Map<String, dynamic> toJson() => {
        'title': title,
        'description': description,
        'linkUrl': linkUrl,
        'ctaNote': ctaNote,
        'imageUrl': imageUrl,
      };
}
