/// Single field definition inside a dynamic Lead Capture Form.
class LeadFormField {
  final String name;
  final String label;
  final String type; // text, email, tel, number, date, textarea
  final String placeholder;
  final bool required;

  const LeadFormField({
    required this.name,
    required this.label,
    this.type = 'text',
    this.placeholder = '',
    this.required = false,
  });

  factory LeadFormField.fromJson(Map<String, dynamic> json) {
    return LeadFormField(
      name: json['name'] ?? '',
      label: json['label'] ?? '',
      type: json['type'] ?? 'text',
      placeholder: json['placeholder'] ?? '',
      required: json['required'] == true,
    );
  }

  Map<String, dynamic> toJson() => {
        'name': name,
        'label': label,
        'type': type,
        'placeholder': placeholder,
        'required': required,
      };
}

/// Payload for an interactive Lead Capture Form.
class FormPayload {
  final String introMessage;
  final List<LeadFormField> fields;
  final String? webhookUrl;

  const FormPayload({
    required this.introMessage,
    required this.fields,
    this.webhookUrl,
  });

  factory FormPayload.fromJson(Map<String, dynamic> json) {
    final fieldsRaw = json['fields'] as List? ?? [];
    return FormPayload(
      introMessage: json['introMessage'] ?? 'Please fill out the form below:',
      fields: fieldsRaw.map((f) => LeadFormField.fromJson(Map<String, dynamic>.from(f))).toList(),
      webhookUrl: json['webhookUrl'],
    );
  }

  /// Parses form definition from HTML generated by CRM Form Builder.
  static FormPayload? parseFromHtml(String html) {
    if (!html.contains("class='form-card'") && !html.contains('class="form-card"')) {
      return null;
    }

    // Extract intro message before the <form> tag
    final formIdx = html.indexOf('<form');
    String intro = formIdx > 0 ? html.substring(0, formIdx).trim() : 'Silakan lengkapi form berikut:';
    intro = intro.replaceAll(RegExp(r'<[^>]*>'), '').trim();

    // Extract webhook URL
    String? webhookUrl;
    final webhookMatch = RegExp(r"fetch\(['\x22](https?:\/\/[^'\x22]+)['\x22]").firstMatch(html);
    if (webhookMatch != null) {
      webhookUrl = webhookMatch.group(1);
    }

    final fields = <LeadFormField>[];
    final inputRegex = RegExp(
      r"<label class=['\x22]form-card_label['\x22]>([^<]+).*?<(input|textarea)\s+type=['\x22]?([a-zA-Z0-9]+)['\x22]?\s+name=['\x22]([a-zA-Z0-9_]+)['\x22]\s+placeholder=['\x22]([^'\x22]*)['\x22](\s+required)?",
      dotAll: true,
    );

    for (final match in inputRegex.allMatches(html)) {
      final label = match.group(1)?.trim() ?? '';
      final type = match.group(3) ?? 'text';
      final name = match.group(4) ?? label.toLowerCase();
      final placeholder = match.group(5) ?? '';
      final isRequired = match.group(6) != null;

      fields.add(LeadFormField(
        name: name,
        label: label,
        type: type,
        placeholder: placeholder,
        required: isRequired,
      ));
    }

    if (fields.isEmpty) {
      // Fallback default lead fields if regex couldn't capture custom fields
      fields.addAll(const [
        LeadFormField(name: 'name', label: 'Full Name', required: true),
        LeadFormField(name: 'email', label: 'Email', type: 'email', required: true),
        LeadFormField(name: 'phone', label: 'Phone Number', type: 'tel'),
      ]);
    }

    return FormPayload(
      introMessage: intro.isEmpty ? 'Silakan lengkapi form berikut:' : intro,
      fields: fields,
      webhookUrl: webhookUrl,
    );
  }

  Map<String, dynamic> toJson() => {
        'introMessage': introMessage,
        'fields': fields.map((f) => f.toJson()).toList(),
        'webhookUrl': webhookUrl,
      };
}
