import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_ai_agent_sdk/flutter_ai_agent_sdk.dart';

void main() {
  group('TEST-AI-U: Functional Model & Parsing Tests', () {
    test('TEST-AI-U01: Should parse QuickReplyOption with pipe syntax accurately', () {
      const raw = 'Jakarta, Bangkok|Bangkok Private Office, KL|Kuala Lumpur Hub';
      final options = QuickReplyOption.parseList(raw);

      expect(options.length, equals(3));
      expect(options[0].label, equals('Jakarta'));
      expect(options[0].value, equals('Jakarta'));

      expect(options[1].label, equals('Bangkok'));
      expect(options[1].value, equals('Bangkok Private Office'));

      expect(options[2].label, equals('KL'));
      expect(options[2].value, equals('Kuala Lumpur Hub'));
    });

    test('TEST-AI-U02: Should parse CardPayload from HTML generated by CRM Card Builder', () {
      const html =
          "<div class='card'><div class='card-title'>Axiata Tower (KL) - Private Office</div><div class='small'>Our private offices are available on flexible terms.<br/><br/>Explore this space in detail here: https://www.ceosuite.com/locations/axiata</div></div><div class='cta-note'>Booking starts from \$15/hour</div>";

      final card = CardPayload.parseFromHtmlOrText(html);

      expect(card, isNotNull);
      expect(card!.title, equals('Axiata Tower (KL) - Private Office'));
      expect(card.description, contains('flexible terms'));
      expect(card.linkUrl, equals('https://www.ceosuite.com/locations/axiata'));
      expect(card.ctaNote, equals('Booking starts from \$15/hour'));
    });

    test('TEST-AI-U03: Should parse FormPayload from HTML generated by CRM Form Builder', () {
      const html =
          "Silakan lengkapi form berikut:<form class='form-card' onsubmit=\"event.preventDefault(); fetch('https://n8n.example.com/webhook/test', {method:'POST'});\"><label class='form-card_label'>Full Name <span class=\"required\">*</span></label><input type='text' name='full_name' placeholder='e.g. John Doe' required/><label class='form-card_label'>WhatsApp Number</label><input type='tel' name='whatsapp' placeholder='0812345678'/><button type='submit'>Submit</button></form>";

      final form = FormPayload.parseFromHtml(html);

      expect(form, isNotNull);
      expect(form!.introMessage, contains('Silakan lengkapi form'));
      expect(form.webhookUrl, equals('https://n8n.example.com/webhook/test'));
      expect(form.fields.length, greaterThanOrEqualTo(2));
      expect(form.fields[0].label, equals('Full Name'));
      expect(form.fields[0].required, isTrue);
    });

    test('TEST-AI-U04: Should auto-detect [HANDOFF_REQUESTED] tag and switch to agent', () {
      const rawReply =
          'Mohon tunggu sebentar, saya sedang menghubungkan Anda dengan representatif CEO Suite... [HANDOFF_REQUESTED]';

      final msg = ChatMessage.fromApiResponse(
        id: 'msg_001',
        rawReply: rawReply,
      );

      expect(msg.isHandoff, isTrue);
      expect(msg.sender, equals(MessageSender.agent));
      expect(msg.text, isNot(contains('[HANDOFF_REQUESTED]')));
      expect(msg.text, contains('menghubungkan Anda'));
    });

    test('TEST-AI-U05: Should handle ResponseType fallback safely on unknown string', () {
      expect(ResponseType.fromString('card'), equals(ResponseType.card));
      expect(ResponseType.fromString('options'), equals(ResponseType.options));
      expect(ResponseType.fromString('form'), equals(ResponseType.form));
      expect(ResponseType.fromString('handoff'), equals(ResponseType.handoff));
      expect(ResponseType.fromString('invalid_type'), equals(ResponseType.text));
      expect(ResponseType.fromString(null), equals(ResponseType.text));
    });
  });
}
